print ("What is your name?")
name = input()
print ("What is your deparment?")
department = input()
print ("What is your email?")
email = input()
print ("What is your badge tier?")
badge = input()
print ("+------------------------------------------+")
print ("|                    Apex Registration Pass|")
print ("|------------------------------------------|")
print ("| ATTENDEE : " + name.ljust(30) + "|")
print ("| ORG      : " + department.ljust(30) + "|")
print ("| CONTACT  : " + email.ljust(30) + "|")
print ("| ACCESS   : " + badge.ljust(30) + "|")
print ("+------------------------------------------+")