print ("What is your name?")
name = input()
print ("What is your deparment?")
department = input()
print ("What is your email?")
email = input()
print ("What is your badge tier?")
badge = input()
print ("+-----------------------+")
print ("| Apex Registration Pass|")
print ("|-----------------------|")
print ("| ATTENDEE : " + name.ljust(11) + "|")
print ("| ORG      : " + department.ljust(11) + "|")
print ("| CONTACT  : " + email.ljust(11) + "|")
print ("| ACCESS   : " + badge.ljust(11) + "|")
print ("+-----------------------+")